package dev.arkoder.inertia4j.typescript;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Pattern;

/**
 * Writes the routes file: a small runtime building URLs, and one route helper per route, nested by route name.
 */
final class RoutesWriter {
    private static final Pattern Identifier = Pattern.compile("[A-Za-z_$][A-Za-z0-9_$]*");
    private static final Set<String> ReservedWords = Set.of(
        "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum",
        "export", "extends", "false", "finally", "for", "function", "if", "import", "in", "instanceof", "new", "null",
        "return", "super", "switch", "this", "throw", "true", "try", "typeof", "var", "void", "while", "with", "yield",
        "let", "static", "implements", "interface", "package", "private", "protected", "public", "await",
        "route", "buildUrl", "queryString", "formDefinition"
    );

    private static final String Runtime = """
        // Generated by Inertia4J. Do not edit.

        export type RouteMethod = 'get' | 'post' | 'put' | 'patch' | 'delete' | 'head' | 'options'

        export interface RouteDefinition<M extends RouteMethod = RouteMethod> {
          url: string
          method: M
        }

        export interface RouteFormDefinition {
          action: string
          method: 'get' | 'post'
        }

        export type RouteParameter = string | number

        export type RouteQueryValue = string | number | boolean | null | undefined | ReadonlyArray<string | number | boolean>

        export interface RouteQueryOptions {
          query?: Record<string, RouteQueryValue>
        }

        export type RouteArguments<A> = [A] extends [void]
          ? [options?: RouteQueryOptions]
          : {} extends A
            ? [args?: A, options?: RouteQueryOptions]
            : [args: A, options?: RouteQueryOptions]

        export type Route<A, P extends RouteMethod, M extends RouteMethod> = ((...args: RouteArguments<A>) => RouteDefinition<P>) & {
          url: (...args: RouteArguments<A>) => string
          form: (...args: RouteArguments<A>) => RouteFormDefinition
          definition: { methods: readonly M[]; url: string }
        } & { [K in M]: (...args: RouteArguments<A>) => RouteDefinition<K> }

        function queryString(query: Record<string, RouteQueryValue> | undefined): string {
          if (!query) {
            return ''
          }

          const search = new URLSearchParams()

          for (const [key, value] of Object.entries(query)) {
            if (value === undefined || value === null) {
              continue
            }

            if (Array.isArray(value)) {
              value.forEach((item) => search.append(key, String(item)))
              continue
            }

            search.append(key, String(value))
          }

          const result = search.toString()

          return result ? `?${result}` : ''
        }

        function buildUrl(template: string, parameters: Record<string, RouteParameter | undefined>, options?: RouteQueryOptions): string {
          const path = template.replace(/(\\/?)\\{(\\*?)(\\w+)(\\??)\\}/g, (_match, slash: string, tail: string, name: string, optional: string) => {
            const value = parameters[name]

            if (value === undefined || value === null || value === '') {
              if (optional || tail) {
                return ''
              }

              throw new Error(`Missing route parameter '${name}' for ${template}`)
            }

            const encoded = tail
              ? String(value).split('/').map(encodeURIComponent).join('/')
              : encodeURIComponent(String(value))

            return slash + encoded
          })

          return (path || '/') + queryString(options?.query)
        }

        function formDefinition(url: string, method: RouteMethod): RouteFormDefinition {
          if (method === 'get' || method === 'post') {
            return { action: url, method }
          }

          return { action: `${url}${url.includes('?') ? '&' : '?'}_method=${method.toUpperCase()}`, method: 'post' }
        }

        function route<A, P extends RouteMethod, M extends RouteMethod = P>(
          template: string,
          methods: readonly [P, ...M[]],
          hasParameters: boolean,
        ): Route<A, P, P | M> {
          const url = (...args: unknown[]): string => {
            const [parameters, options] = hasParameters ? [args[0], args[1]] : [undefined, args[0]]

            return buildUrl(template, (parameters ?? {}) as Record<string, RouteParameter | undefined>, options as RouteQueryOptions | undefined)
          }
          const callable = (...args: unknown[]): RouteDefinition<P> => ({ url: url(...args), method: methods[0] })
          const helpers: Record<string, unknown> = {
            url,
            form: (...args: unknown[]) => formDefinition(url(...args), methods[0]),
            definition: { methods, url: template },
          }

          for (const method of methods) {
            helpers[method] = (...args: unknown[]): RouteDefinition<RouteMethod> => ({ url: url(...args), method })
          }

          return Object.assign(callable, helpers) as unknown as Route<A, P, P | M>
        }
        """;

    private RoutesWriter() {}

    static String write(List<RouteEntry> routes) {
        Map<String, Object> tree = tree(routes);
        StringBuilder out = new StringBuilder(Runtime);

        tree.forEach((name, node) -> {
            out.append('\n');

            if (!Identifier.matcher(name).matches() || ReservedWords.contains(name)) {
                throw new GenerationException(
                    "Route group '" + name + "' is not a valid TypeScript identifier. Rename the controller or the route."
                );
            }

            out.append("export const ").append(name).append(" = ");
            writeNode(out, node, 0);
            out.append('\n');
        });

        return out.toString();
    }

    private static Map<String, Object> tree(List<RouteEntry> routes) {
        Map<String, Object> root = new LinkedHashMap<>();

        for (RouteEntry route : routes) {
            if (route.name().size() < 2) {
                throw new GenerationException(
                    "Route '" + route.qualifiedName() + "' (" + route.template() + ") needs a group and a name, such as 'users.show'"
                );
            }

            Map<String, Object> node = root;
            List<String> groups = route.name().subList(0, route.name().size() - 1);

            for (String group : groups) {
                Object child = node.computeIfAbsent(group, key -> new LinkedHashMap<String, Object>());

                if (!(child instanceof Map<?, ?>)) {
                    throw conflict(route);
                }

                @SuppressWarnings("unchecked")
                Map<String, Object> childNode = (Map<String, Object>) child;
                node = childNode;
            }

            String leaf = route.name().get(route.name().size() - 1);

            if (node.containsKey(leaf)) {
                throw conflict(route);
            }

            node.put(leaf, route);
        }

        return root;
    }

    private static GenerationException conflict(RouteEntry route) {
        return new GenerationException(
            "Route name '" + route.qualifiedName() + "' (" + route.template() + ") is used by more than one route or group"
        );
    }

    private static void writeNode(StringBuilder out, Object node, int depth) {
        if (node instanceof RouteEntry route) {
            writeRoute(out, route);
            return;
        }

        @SuppressWarnings("unchecked")
        Map<String, Object> children = (Map<String, Object>) node;
        String indent = "  ".repeat(depth + 1);

        out.append("{\n");

        children.forEach((key, child) -> {
            out.append(indent).append(propertyName(key)).append(": ");
            writeNode(out, child, depth + 1);
            out.append(",\n");
        });

        out.append("  ".repeat(depth)).append('}');
    }

    private static void writeRoute(StringBuilder out, RouteEntry route) {
        List<RouteEntry.RouteParameter> parameters = route.parameters();
        String primary = quote(route.methods().get(0));
        List<String> methods = new ArrayList<>();
        route.methods().forEach(method -> methods.add(quote(method)));
        String others = methods.size() > 1 ? ", " + String.join(" | ", methods.subList(1, methods.size())) : "";

        out.append("route<").append(argumentsType(parameters)).append(", ").append(primary).append(others).append(">(")
            .append(quote(route.template())).append(", [").append(String.join(", ", methods)).append("], ")
            .append(!parameters.isEmpty()).append(')');
    }

    private static String argumentsType(List<RouteEntry.RouteParameter> parameters) {
        if (parameters.isEmpty()) {
            return "void";
        }

        List<String> fields = new ArrayList<>();

        for (RouteEntry.RouteParameter parameter : parameters) {
            fields.add(propertyName(parameter.name()) + (parameter.optional() ? "?: " : ": ") + "RouteParameter");
        }

        return "{ " + String.join("; ", fields) + " }";
    }

    private static String propertyName(String name) {
        if (Identifier.matcher(name).matches()) {
            return name;
        }

        return quote(name);
    }

    private static String quote(String value) {
        return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'";
    }
}
