package dev.arkoder.inertia4j.typescript;

import java.util.Comparator;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

/**
 * Renders a {@link TsModel} as the content of a {@code .d.ts} file.
 */
final class TypeScriptWriter {
    private static final Pattern Identifier = Pattern.compile("[A-Za-z_$][A-Za-z0-9_$]*");

    private TypeScriptWriter() {}

    static String write(TsModel model) {
        StringBuilder out = new StringBuilder();
        out.append("// Generated by Inertia4J. Do not edit.\n");
        out.append("import '@inertiajs/core'\n");

        model.declarations().stream()
            .sorted(Comparator.comparing(TsDeclaration::name))
            .forEach(declaration -> {
                out.append('\n');
                writeDeclaration(out, declaration);
            });

        out.append('\n');
        writePages(out, model);
        out.append("\nexport type PageProps<C extends keyof InertiaPages> = InertiaPages[C]\n");
        out.append('\n');
        writeConfig(out, model);

        return out.toString();
    }

    private static void writeDeclaration(StringBuilder out, TsDeclaration declaration) {
        if (declaration instanceof TsDeclaration.Enum enumDeclaration) {
            String values = enumDeclaration.values().isEmpty()
                ? "never"
                : enumDeclaration.values().stream().map(TypeScriptWriter::quote).collect(Collectors.joining(" | "));
            out.append("export type ").append(enumDeclaration.name()).append(" = ").append(values).append('\n');
            return;
        }

        TsDeclaration.Interface interfaceDeclaration = (TsDeclaration.Interface) declaration;
        out.append("export interface ").append(interfaceDeclaration.name());

        if (!interfaceDeclaration.typeParameters().isEmpty()) {
            out.append('<').append(String.join(", ", interfaceDeclaration.typeParameters())).append('>');
        }

        if (interfaceDeclaration.properties().isEmpty()) {
            out.append(" {}\n");
            return;
        }

        out.append(" {\n");
        for (TsDeclaration.Property property : interfaceDeclaration.properties()) {
            out.append("  ")
                .append(propertyName(property.name()))
                .append(property.optional() ? "?: " : ": ")
                .append(property.type().render())
                .append('\n');
        }
        out.append("}\n");
    }

    private static void writePages(StringBuilder out, TsModel model) {
        if (model.pages().isEmpty()) {
            out.append("export interface InertiaPages {}\n");
            return;
        }

        out.append("export interface InertiaPages {\n");
        model.pages().forEach((component, type) ->
            out.append("  ").append(quote(component)).append(": ").append(type).append('\n')
        );
        out.append("}\n");
    }

    private static void writeConfig(StringBuilder out, TsModel model) {
        out.append("declare module '@inertiajs/core' {\n");
        out.append("  export interface InertiaConfig {\n");

        if (!model.sharedTypes().isEmpty()) {
            out.append("    sharedPageProps: ").append(String.join(" & ", model.sharedTypes())).append('\n');
        }

        if (!model.flashTypes().isEmpty()) {
            out.append("    flashDataType: ").append(String.join(" & ", model.flashTypes())).append('\n');
        }

        out.append("    errorValueType: ").append(model.errorValueType().typeScript()).append('\n');
        out.append("  }\n");
        out.append("}\n");
    }

    private static String propertyName(String name) {
        if (Identifier.matcher(name).matches()) {
            return name;
        }

        return quote(name);
    }

    private static String quote(String value) {
        return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'";
    }
}
