package dev.arkoder.inertia4j.typescript;

import org.junit.jupiter.api.Test;

import java.util.List;

import static dev.arkoder.inertia4j.typescript.GeneratorTestSupport.assertContains;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class RoutesWriterTest {
    @Test
    void routesAreGroupedByTheirName() {
        String content = RoutesWriter.write(List.of(
            new RouteEntry(List.of("UsersController", "index"), List.of("get"), "/users"),
            new RouteEntry(List.of("UsersController", "show"), List.of("get"), "/users/{id}"),
            new RouteEntry(List.of("admin", "reports", "export"), List.of("post", "put"), "/admin/reports/{year}/{month?}")
        ));

        assertContains(content, """
            export const UsersController = {
              index: route<void, 'get'>('/users', ['get'], false),
              show: route<{ id: RouteParameter }, 'get'>('/users/{id}', ['get'], true),
            }
            """);
        assertContains(content, """
            export const admin = {
              reports: {
                export: route<{ year: RouteParameter; month?: RouteParameter }, 'post', 'put'>('/admin/reports/{year}/{month?}', ['post', 'put'], true),
              },
            }
            """);
    }

    @Test
    void theRuntimeIsWrittenFirst() {
        String content = RoutesWriter.write(List.of());

        assertTrue(content.startsWith("// Generated by Inertia4J. Do not edit.\n"), content);
        assertContains(content, "function route<A, P extends RouteMethod, M extends RouteMethod = P>(");
    }

    @Test
    void aNameUsedTwice_isRejected() {
        GenerationException exception = assertThrows(GenerationException.class, () -> RoutesWriter.write(List.of(
            new RouteEntry(List.of("users", "show"), List.of("get"), "/users/{id}"),
            new RouteEntry(List.of("users", "show"), List.of("get"), "/people/{id}")
        )));

        assertTrue(exception.getMessage().contains("users.show"), exception.getMessage());
    }

    @Test
    void aRouteNamedLikeAGroup_isRejected() {
        assertThrows(GenerationException.class, () -> RoutesWriter.write(List.of(
            new RouteEntry(List.of("users", "show"), List.of("get"), "/users/{id}"),
            new RouteEntry(List.of("users", "show", "posts"), List.of("get"), "/users/{id}/posts")
        )));
    }

    @Test
    void aGroupThatIsNotAnIdentifier_isRejected() {
        GenerationException exception = assertThrows(GenerationException.class, () -> RoutesWriter.write(List.of(
            new RouteEntry(List.of("delete", "all"), List.of("delete"), "/all")
        )));

        assertTrue(exception.getMessage().contains("'delete'"), exception.getMessage());
    }

    @Test
    void normalizeTemplate_dropsParameterConstraints() {
        assertEquals("/orders/{id}/{*path}", RouteEntry.normalizeTemplate("/orders/{id:\\d{3}}/{*path}"));
        assertEquals("/users/{id}", RouteEntry.normalizeTemplate("/users/{id:[0-9]+}"));
    }

}
