package dev.arkoder.inertia4j.typescript;

import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.TreeMap;

import static org.junit.jupiter.api.Assertions.assertEquals;

class TypeScriptWriterTest {
    @Test
    void write_rendersDeclarationsPagesAndConfig() {
        TsType.Reference status = new TsType.Reference("Status", List.of());
        TsType.Reference stat = new TsType.Reference("Stat", List.of());

        TsModel model = new TsModel(
            List.of(
                new TsDeclaration.Interface("Stat", List.of(), List.of(
                    new TsDeclaration.Property("label", TsType.StringKeyword, false),
                    new TsDeclaration.Property("value", TsType.NumberKeyword, false)
                )),
                new TsDeclaration.Enum("Status", List.of("Active", "It's archived")),
                new TsDeclaration.Interface("Page", List.of("T"), List.of(
                    new TsDeclaration.Property("items", new TsType.Array(new TsType.Variable("T")), false)
                )),
                new TsDeclaration.Interface("IndexProps", List.of(), List.of(
                    new TsDeclaration.Property("stats", new TsType.Array(stat), true),
                    new TsDeclaration.Property("nickname", TsType.nullable(TsType.StringKeyword), false),
                    new TsDeclaration.Property("tags", new TsType.Array(TsType.nullable(TsType.StringKeyword)), false),
                    new TsDeclaration.Property("counts", new TsType.StringMap(TsType.NumberKeyword), false),
                    new TsDeclaration.Property("byId", new TsType.NumberMap(TsType.StringKeyword), false),
                    new TsDeclaration.Property("byStatus", new TsType.EnumMap(status, TsType.NumberKeyword), false),
                    new TsDeclaration.Property("page", new TsType.Reference("Page", List.of(stat)), false),
                    new TsDeclaration.Property("first-name", TsType.StringKeyword, false)
                )),
                new TsDeclaration.Interface("Empty", List.of(), List.of())
            ),
            new TreeMap<>(java.util.Map.of("Stats/Index", "IndexProps")),
            List.of("AppShared", "AuthShared"),
            ErrorValueType.StringArray
        );

        String expected = """
            // Generated by Inertia4J. Do not edit.
            import '@inertiajs/core'

            export interface Empty {}

            export interface IndexProps {
              stats?: Stat[]
              nickname: string | null
              tags: (string | null)[]
              counts: { [key: string]: number }
              byId: { [key: number]: string }
              byStatus: { [key in Status]?: number }
              page: Page<Stat>
              'first-name': string
            }

            export interface Page<T> {
              items: T[]
            }

            export interface Stat {
              label: string
              value: number
            }

            export type Status = 'Active' | 'It\\'s archived'

            export interface InertiaPages {
              'Stats/Index': IndexProps
            }

            export type PageProps<C extends keyof InertiaPages> = InertiaPages[C]

            declare module '@inertiajs/core' {
              export interface InertiaConfig {
                sharedPageProps: AppShared & AuthShared
                errorValueType: string[]
              }
            }
            """;

        assertEquals(expected, TypeScriptWriter.write(model));
    }

    @Test
    void write_withoutSharedTypesOrPages_omitsSharedPageProps() {
        TsModel model = new TsModel(List.of(), new TreeMap<>(), List.of(), ErrorValueType.String);

        String expected = """
            // Generated by Inertia4J. Do not edit.
            import '@inertiajs/core'

            export interface InertiaPages {}

            export type PageProps<C extends keyof InertiaPages> = InertiaPages[C]

            declare module '@inertiajs/core' {
              export interface InertiaConfig {
                errorValueType: string
              }
            }
            """;

        assertEquals(expected, TypeScriptWriter.write(model));
    }

    @Test
    void write_withEmptyEnum_rendersNever() {
        TsModel model = new TsModel(List.of(new TsDeclaration.Enum("Nothing", List.of())), new TreeMap<>(), List.of(), ErrorValueType.String);

        assertEquals(true, TypeScriptWriter.write(model).contains("export type Nothing = never\n"));
    }
}
