// Generated by Inertia4J. Do not edit.
import '@inertiajs/core'

export interface Album {
  id: number
  title: string
  status: Status
}

export interface AlbumsIndexProps {
  albums: Album[]
  stats?: Stat[]
}

export interface AppShared {
  user: User | null
  appName: string
}

export interface CreateAlbumForm {
  title: string
  status: Status
}

export interface Stat {
  label: string
  value: number
}

export type Status = 'Active' | 'Archived'

export interface User {
  id: number
  name: string
}

export interface InertiaPages {
  'Albums/Index': AlbumsIndexProps
}

export type PageProps<C extends keyof InertiaPages> = InertiaPages[C]

declare module '@inertiajs/core' {
  export interface InertiaConfig {
    sharedPageProps: AppShared
    errorValueType: string
  }
}
